### ISSUE TITLE
Support more modern PHP versions out of the box.

### ISSUE THREAD

**Issue by damacus** [sous-chefs/php#224]
This will probably require some extra channels and what not, ( e.g. [using this PPA on Ubuntu for 7.2](https://launchpad.net/~ondrej/+archive/ubuntu/php) ). But I think it's worth it.

**Comment by jeffbyrnes** [comment]
With Ubuntu 18.04 & 20.04, the default versions of PHP that are installed are 7.2, and 7.4, respectively, which may make this issue moot.

Thoughts, @damacus?

**Comment by damacus** [comment]
That solves it for Ubuntu but not rhel/centos/debian. It's nice that we get those out of the box. Also ideally we would be able to install 7.4 on 18.04

**Comment by jeffbyrnes** [comment]
@damacus certainly we could use a PPA to give 18.04 the ability to install more modern versions.

For the time being, my effort is to get this cookbook to support all the current supported OS versions, and whatever PHP version they include as their default packaging.

I think providing for using a PPA is something we can consider in a larger refactor to convert this cookbook to use resources instead of recipes + attributes.

RHEL/CentOS/Debian are certainly their own kettle of fish, and we should at least support those (and probably Amazon Linux 2). Might be helpful to drop the other distros to focus our efforts?

**Comment by jeffbyrnes** [comment]
@damacus, things are fixed up nicely now, and you can install a newer version by building from source, at least. Do you think that‘s enough? I’m wary of trying to add PPA support.

**Comment by axl89** [comment]
>I’m wary of trying to add PPA support.

I believe I understand this point, but as a sysadmin with lots of PHP systems to build and give support to while being compliant with strict security policies, I have to say that compiling from source is not always an option, especially for production systems, since having a compilation toolkit in production may rise some alarms and I believe it is not considered a good practice in terms of security, or so I've read in some CIS hardening benchmarks.

Now, this doesn't mean I'm a fan of using unofficial repositories like the [Ondřej Surý one](https://launchpad.net/~ondrej/+archive/ubuntu/php), but having to chose between compiling in production and this... I'd pick the unofficial-yet-famous repository.

Hope I brought a different angle to this discussion :smile:

**Comment by jeffbyrnes** [comment]
@axl89 very good points all around, you’ve convinced me.

And we can always refactor & change it up if something arises that makes it easier to avoid the PPA (or it becomes clearly unsafe).

**Comment by jeffbyrnes** [comment]
Looks like for RHEL family distros, we can use the [REMI repository](https://rpms.remirepo.net/).
